version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hotel_booking_server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://irshad:jHvCyPbXWcktY7Yc@cluster0.jm9yi6w.mongodb.net/hotel_booking?retryWrites=true&w=majority&appName=Cluster0
      - PORT=4000
    volumes:
      - ./server:/app
      - /app/node_modules

  react_native:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: hotel_booking_client
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./client:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal