version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hotel_booking_server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://irshad:jHvCyPbXWcktY7Yc@cluster0.jm9yi6w.mongodb.net/hotel_booking?retryWrites=true&w=majority&appName=Cluster0
      - PORT=4000
    volumes:
      - ./server:/app
      - /app/node_modules

  react_native:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./react_native_app:/opt/react_native_app/app:delegated
      - ./react_native_app/package.json:/opt/react_native_app/package.json
      - ./react_native_app/package-lock.json:/opt/react_native_app/package-lock.json
      - notused:/opt/react_native_app/app/node_modules
    container_name: hotel_booking_client
    environment:
      - EXPO_WEB_HOSTNAME=0.0.0.0
volumes:
  notused: